version: "3.8"
services:
  frontend:
    build:
        context: ./frontend
        dockerfile: ./Dockerfile
    ports:
        - "3000:3000"
    depends_on:
        - "backend"
    links:
        - "backend"

  backend:
    build:
        context: ./backend
        dockerfile: ./Dockerfile

networks:
    default:
        name: url-shortener